### PR TITLE
Sex is not translated in Frontend

### LINKED ISSUE #455: Show "Hona" "Hane" in frontend
In 
individual_view
herd_view 
and 
genebank_view 

Show swedish Hane and Hone instead of male and female.

### PR DESCRIPTION
**Pull request by jhagberg**
This closes #455 
commit 2 fixes the fillter table

### CODE REVIEW

**Comment by jhagberg** [comment]
There are more places that sex is still the same as what is stored in database. 
One way is to translate in the backend but many functions in the frontend are using English values.

**Comment by HenrikeW** [comment]
Works! Do you want to fix the table before merging so that #455 actually can be closed? 
Otherwise remember re-opening 455 after merging or changing the description above before merging so that the issue isn't closed and disappears without being properly resolved.

**Comment by jhagberg** [comment]
Filter table is fixed in my second commit.

**Comment by HenrikeW** [comment]
It works in the genebank view, where you see the big table with all rabbits. If I want to look at a herd view I get an error saying `rowData.herd is undefined`. Not sure if this is expected? If yes, it's fine to merge,

**Comment by jhagberg** [comment]
Yes that error sometimes popus for me also. Did not see it now.

**Review by HenrikeW — APPROVED** [review]

**Pull request merged**
