### PR TITLE
Make sure all individuals have a breeding

### LINKED ISSUE #222: Import script is not creating breeding IDs for founders
Founder animals without mother and father does not have a breeding value/event and thus no breeding ID in the indvidual table

### PR DESCRIPTION
**Pull request by pontus**

### CODE REVIEW

**Comment by jhagberg** [comment]
Wee need the same for Mellerud data right?

**Review by jhagberg — CHANGES_REQUESTED** [review]
Import seems to work. But when running the DB container spits out lots of errors 

`2021-02-26 08:47:59.441 UTC [33] ERROR:  column i.father_id does not exist at character 341`

**Comment by jhagberg** [comment]
```
2021-02-26 08:51:24.755 UTC [47] ERROR:  column i.father_id does not exist at character 341
herdbook-db | 2021-02-26 08:51:24.755 UTC [47] STATEMENT:  SELECT      i.number as Indiv, f.number as Sire, m.number as Dam, i.sex as Sex, i.birth_date as Born, 
herdbook-db | 	            (i.death_date IS NULL
herdbook-db | 	             AND (i.death_note = '' OR i.death_note IS NULL)
herdbook-db | 	             AND ih.herd_tracking_date > current_date - interval '1 year') AS is_active
herdbook-db | 	FROM        individual i
herdbook-db | 	LEFT JOIN   individual f ON (i.father_id = f.individual_id)
herdbook-db | 	LEFT JOIN   individual m ON (i.mother_id = m.individual_id)
herdbook-db | 	JOIN        (
herdbook-db | 	                SELECT DISTINCT ON (individual_id)
herdbook-db | 	                         individual_id,
herdbook-db | 	                         herd_id,
herdbook-db | 	                         herd_tracking_date
herdbook-db | 	                FROM     herd_tracking
herdbook-db | 	                ORDER BY individual_id, herd_tracking_date DESC
herdbook-db | 	            ) AS ih ON (ih.individual_id = i.individual_id)
herdbook-db | 	JOIN        herd h ON (ih.herd_id = h.herd_id)
herdbook-db | 	WHERE       h.genebank_id =1
```

**Review by andkaha — APPROVED** [review]
This looks ok.

**Comment by pontus** [comment]
I think what @jhagberg  saw was due to running with the old R api solution. (And if so; can the changes requested be removed?)

As mentioned, should we set up the same in Mellerud as well (if one only loads that)?

**Comment by andkaha** [comment]
> I think what @jhagberg saw was due to running with the old R api solution. (And if so; can the changes requested be removed?)

I think that may be correct. I could override the change request and merge, maybe?

> 
> As mentioned, should we set up the same in Mellerud as well (if one only loads that)?

I did (see commit).  The Gotland data is loaded first anyway, so the Mellerud load script needs to do the same thing anyway.

**Pull request merged**
