### PR TITLE
Feature/schema tweaks

### LINKED ISSUE #1: Finish schema
Finish the database schema.

### PR DESCRIPTION
**Pull request by andkaha**
Changes:

* Uniqueness constraints on `genebank.name` and `colour.name`.
* In individual, change the unique constraint on `name` to _include_ `genebank_id`.

### CODE REVIEW

**Review by norling — CHANGES_REQUESTED** [review]
Wouldn't it make more sense to set `individual.certificate` as `UNIQUE` right away, and just not be able to load all the data until it's fixed? To me, making schema changes later seems a lot more involved than reloading the data later.

**Comment by pontus** [comment]
Is the number collision free between the two genebanks? The weakened constraint looks sensible to me (in general).

**Review by pontus — APPROVED** [review]
Looks ok.

**Comment by andkaha** [comment]
@norling I think it's unreasonable to block the entire project until the data is fixed. In the Gottlandskanin data set there are 370 missing or duplicated certificates, and in the Mellerud set there are 72.

**Pull request merged**
