### PR TITLE
Use / as last resort for non-existant URIs.

### PR DESCRIPTION
**Pull request by pontus**

### CODE REVIEW

**Review by jhagberg — CHANGES_REQUESTED** [review]
This does not work just get me a blank page

**Comment by pontus** [comment]
Odd, but this seems to work for me now at least.

**Comment by jhagberg** [comment]
Running this is one step forward but still does not work. It now generates the root page on all subdirectory access. 
 For example "http://localhost:8080/genebank/Gotlandskanin" rewrites to /

**Comment by jhagberg** [comment]
grejt this seams to work!

**Review by jhagberg — COMMENTED** [review]
Looks like it works now

**Review by jhagberg — APPROVED** [review]

**Pull request merged**
