### PR TITLE
List breeding events using herd tracking and current mothers in herd

### PR DESCRIPTION
**Pull request by jhagberg**
This will fix the breeding list to list breedings distinct breeding events for mothers in current herd or for any mother that have a herd tracking entry for the current herd. 

Shows both breeding and births. 

TO DO . perhaps faster to use iterator() or object() operator

### CODE REVIEW

**Comment by jhagberg** [comment]
This work good on current imported data. But will probably fail if you are buying a female from another herd that had a breeding event the same year in that herd. So we need to check, herd tracking date < breeding birth date

**Comment by jhagberg** [comment]
If we got offspring this select will get every breeding event origin from the herd
but are missing breeding events with no offsprings. Can combine and UNION with the old statement perhaps

```
query = (
                Breeding.select()
                .join(Individual, on=(Breeding.id == Individual.breeding))
                .join(Herd, on=(Herd.id == Individual.origin_herd))
                .where((Herd.herd == herd_id))
                .distinct()
            )
```
That peewee code is for example:

`SELECT DISTINCT "t1"."breeding_id", "t1"."breed_date", "t1"."breed_notes", "t1"."birth_date", "t1"."birth_notes", "t1"."litter_size", "t1"."father_id", "t1"."mother_id" FROM "breeding" AS "t1" INNER JOIN "individual" AS "t2" ON ("t1"."breeding_id" = "t2"."breeding_id") INNER JOIN "herd" AS "t3" ON ("t3"."herd_id" = "t2"."origin_herd_id") WHERE ("t3"."herd" = 'G1274');`

**Comment by jhagberg** [comment]
and this is a example of a Union: 

`(SELECT DISTINCT "t1"."breeding_id", "t1"."breed_date", "t1"."breed_notes", "t1"."birth_date", "t1"."birth_notes", "t1"."litter_size", "t1"."father_id", "t1"."mother_id" FROM "breeding" AS "t1" INNER JOIN "individual" AS "t2" ON ("t1"."mother_id" = "t2"."individual_id") WHERE ("t2"."individual_id" IN (324, 379, 1391, 5373, 6385, 11457, 13988, 13989, 13990, 13991, 13998, 13999, 14000, 14001, 14002, 14003))) UNION (SELECT DISTINCT "t3"."breeding_id", "t3"."breed_date", "t3"."breed_notes", "t3"."birth_date", "t3"."birth_notes", "t3"."litter_size", "t3"."father_id", "t3"."mother_id" FROM "breeding" AS "t3" INNER JOIN "individual" AS "t4" ON ("t3"."breeding_id" = "t4"."breeding_id") INNER JOIN "herd" AS "t5" ON ("t5"."herd_id" = "t4"."origin_herd_id") WHERE ("t5"."herd" = 'G1274'));`

**Comment by jhagberg** [comment]
That works if you have offspring registered in the genebank. But If I buy a rabbit that has bred in another genebank I do not want to list that breeding event.

Is there a SQL way to figure out from herd_tracking  to the interval when a individual has belonged to a herd. like start date and end date?

**Comment by andkaha** [comment]
> Is there a SQL way to figure out from herd_tracking to the interval when a individual has belonged to a herd. like start date and end date?

```
WITH    start_dates AS (
        SELECT  individual_id, herd_id,
                MIN(herd_tracking_date) as "start_date"
        FROM    herd_tracking
        GROUP BY        individual_id, herd_id
        ),
        end_dates AS (
        SELECT  individual_id, start.herd_id,
                MIN(ht.herd_tracking_date) as "end_date"
        FROM    start_dates start
        JOIN    herd_tracking ht USING (individual_id)
        WHERE   ht.herd_tracking_date > start.start_date
        AND     ht.herd_id != start.herd_id
        GROUP BY        individual_id, start.herd_id
        )
SELECT  individual_id,
        start.herd_id, start.start_date,
        "end".end_date
FROM    start_dates start
LEFT JOIN       end_dates "end" USING (individual_id, herd_id)
ORDER BY        individual_id, start.start_date;
```

Example output for some individual `51` and `1940`:
```
 individual_id | herd_id | start_date |  end_date
---------------+---------+------------+------------
            51 |       7 | 2018-05-17 | 2018-12-31
            51 |     438 | 2018-12-31 | 2020-12-31
            51 |     800 | 2020-12-31 |
          1940 |     122 | 2017-08-17 | 2018-12-31
          1940 |     465 | 2018-12-31 | 2021-09-16
          1940 |       1 | 2021-09-16 |

```

For these individuals we have the following entries in the `herd_tracking` table:
```
herdbook=# select * from herd_tracking where individual_id in (51,1940);
 herd_tracking_id | from_herd_id | herd_id | signature_id | individual_id | herd_tracking_date
------------------+--------------+---------+--------------+---------------+--------------------
               51 |              |       7 |              |            51 | 2018-05-17
            24180 |              |     438 |              |            51 | 2018-12-31
            25230 |              |     438 |              |            51 | 2019-12-31
            26291 |              |     800 |              |            51 | 2020-12-31
             1940 |              |     122 |              |          1940 | 2017-08-17
            24457 |              |     465 |              |          1940 | 2018-12-31
            25487 |              |     465 |              |          1940 | 2019-12-31
            26541 |              |     465 |              |          1940 | 2020-12-31
            27519 |              |       1 |              |          1940 | 2021-09-16
(9 rows)

```

**Comment by jhagberg** [comment]
This is outdated

**Pull request closed without merging**
