### PR TITLE
Feature/replace yarn with npm

### PR DESCRIPTION
**Pull request by inghylt**
Please try out the new changes on your computers. Recommended to run

`docker-compose rm -sfv`
`rm -rf frontend/dist`
`rm -rf frontend/node_modules`
`docker-compose build herdbook-frontend-devel main` (or the whole docker environment if you are not in a hurry)

### CODE REVIEW

**Comment by pontus** [comment]
Seems to work like previously.

**Review by pontus — APPROVED** [review]
Seems to work for prebuilt. I have not tested/thought about behaviour with snowpack.

**Review by norling — APPROVED** [review]
Seems to work just as intended! :)

**Comment by danr** [comment]
That's some dank commit messages right there :100: :1st_place_medal:

**Pull request merged**
