### PR TITLE
Herd view table updates automatically

### LINKED ISSUE #404: Update my herd individual list
Add rabbit and update rabbit should trigger a reload of rabbit list in my herd so that the changes to rabbits and newly rabbits will show up without user have to reload the whole page.

### PR DESCRIPTION
**Pull request by HenrikeW**
If a user looks at a herd in herd view, the shown table in the tab "Lista över individer" will now update automatically as soon as one of the herd's individuals is updated, added or removed from the herd. 

To achieve that, the following changes were made:
- the `get_herd` function in `data_access.py` now sends more detailed information about a herd's individuals
- `herd_view.tsx` will take its information for the table of individuals from the herd instead of the big `genebanks`variable created on page load
- the `filter_table`was adjusted to be able to take in the information on `color` sent from the backend (in a different format as before). Also the table now can show digital certificate numbers.
- the tab "Lista över individer" will fetch herd data every time it's clicked
- the global `data_context` now has listeners for the herd the user is currently looking at as well as changes that are made to individuals in that herd. Changes can be made through
1. Editing an individual
2. issuing a digital certificate
3. updating a digital certificate
4. reporting an individual as dead
5. creating empty individuals when adding a breeding
6. selling an individual

All the components for these actions are now linked to the listener.

fixes #404

### CODE REVIEW

**Review by jhagberg — CHANGES_REQUESTED** [review]
Cant list live active animals need to click "visa döda" and "visa inaktiva djur" to be able to list

**Comment by jhagberg** [comment]
Cant no longer list GX1 herds

**Comment by jonandernovella** [comment]
The GX1 loading bug seems to be on the new frontend updates. @HenrikeW tested without @jhagberg 's changes

**Comment by jhagberg** [comment]
Think its because we changed short_info to as_dict and that needs to do more lookups
 and fails on big data

**Comment by jhagberg** [comment]
To reproduce this
checkout develop
start your docker

Test and list GX1 
then change  line 643 in data_access to 
        `   data["individuals"] = [i.as_dict() for i in herd.individuals]` 

try list GX1 again

then you get 502

**Review by jhagberg — APPROVED** [review]
Works for now!

**Pull request merged**
