### PR TITLE
Update doc strings for the R-api

### PR DESCRIPTION
**Pull request by jhagberg**

### CODE REVIEW

**Review by pontus — APPROVED** [review]

**Comment by pontus** [comment]
What standard are we using for R docstrings?

**Comment by jhagberg** [comment]
no real standard :) it can be improved!

**Comment by jhagberg** [comment]
Yes there is no real doc-strings in R but we could use a package and do something like this 
https://cran.r-project.org/web/packages/docstring/vignettes/docstring_intro.html

**Review by pontus — APPROVED** [review]

**Comment by norling** [comment]
I was thinking that you should add docstrings for the R-API functions in `herdbook.py`. But the R scripts but this is also good! :)

**Pull request merged**
