### PR TITLE
fixed register popup link öppna i eget fonster

### PR DESCRIPTION
**Pull request by airenzp**
Closes issue #388 and #380

### CODE REVIEW

**Review by jhagberg — CHANGES_REQUESTED** [review]
This won't work if you are only a herd owner. You are not allowed to access /register 
Can we just disable the "öppna i eget fönster" if you are a herd owner?

**Comment by airenzp** [comment]
But if you are at the popup, I guess you had the rights, what should be hidden would be the lägg till. Maybe it was, I did not test this use case.

**Comment by jhagberg** [comment]
Yes maybe we should enable the register rabbit to work for Herd owner also
If you ad a user with your admin rights and only give it access to a herd then you should be able to see that you cant access /register but you can access the form via the button "lägg till" on the herd page

**Comment by airenzp** [comment]
Does this has any effect on the changes here? If not maybe I can merge this PR.

**Comment by jhagberg** [comment]
Yes since this changes will not work for herd owner

**Comment by airenzp** [comment]
Left undefined the dialogLink parameter in the popup so that the button oppna i eget fonster is hidden:

`<DialogActions>
          {dialogLink && (
            <Link to={dialogLink} target="_blank">
              <Button color="primary">Öppna i eget fönster</Button>
            </Link>
          )}
          <Button onClick={handleCloseDialog} color="primary">
            Stäng
          </Button>
        </DialogActions>
`

**Review by jhagberg — APPROVED** [review]

**Pull request merged**
