### PR TITLE
Css/basic layout

### PR DESCRIPTION
**Pull request by norling**
probably a bunch of fiddling left, but is this a good start or should I work on some other idea?

### CODE REVIEW

**Review by jhagberg — DISMISSED** [review]
Esbuild build.sh scripts needs update to handle png jpg.
Should the images be put in a subfolder?

**Comment by jhagberg** [comment]
@pontus I can get the images to load does this has something to do with Nginx?

**Comment by e0** [comment]
@jhagberg I tried running this branch locally and the frontend container crashes with the error `snowpack: not found`. I suspect that's why the images are not loading either.

**Comment by pontus** [comment]
Yep, this is nginx (over-)compensating for react. It also seems images are not copied into the main image as needed for them to be served, so I/someone still need to troubleshoot that.

**Comment by pontus** [comment]
Pre-built images work for me now.

**Review by airenzp — APPROVED** [review]
Great improvement to the interface!!!
I added some minor changes

**Pull request merged**
