### PR TITLE
Added workflow to publish container packages

### PR DESCRIPTION
**Pull request by pontus**

### CODE REVIEW

**Comment by jhagberg** [comment]
so What will this do build and publish images on push to Develop?

**Comment by pontus** [comment]
Current behaviour is to build for all pushes. Tagged as the last part of the branch name if not in a special branch whereas for main, master and develop it will tag with latest instead.
 
The intent is that this should help with caching user side as well, but some more investigation is required there.

**Review by jhagberg — APPROVED** [review]
Works but needs some hack to get the cache locally. Need documentation

**Comment by pontus** [comment]
Merged this now and will continue in another PR.

**Pull request merged**
