### PR TITLE
Fetch from API to R services.

### PR DESCRIPTION
**Pull request by pontus**

### CODE REVIEW

**Comment by pontus** [comment]
I think this should be ok now.

**Comment by pontus** [comment]
Rebased.

**Comment by jhagberg** [comment]
Testing now getting following error
```
Error in stopOnLine(lineNum, file[lineNum], e) : 
r-api       |   Error on line #240: '#RUN stuff and preload' - Error in url(paste0(api_base, resource), headers = our_headers()): 'headers' must have names and must not be NA
r-api       | Calls: <Anonymous> ... tryCatchList -> tryCatchOne -> <Anonymous> -> stopOnLine
r-api       | Execution halted

```

**Review by jhagberg — APPROVED** [review]
This Works good with my latest Commit

**Comment by jhagberg** [comment]
Getting this error from the docker container 
```
Warning messages:
r-api       | 1: In nPed_fixed[] <- numPed(ped_fixed_ord, check = FALSE) :
r-api       |   number of items to replace is not a multiple of replacement length
r-api       | 2: In nPed_fixed[] <- numPed(ped_fixed_ord, check = FALSE) :
r-api       |   number of items to replace is not a multiple of replacement length
r-api       | Running plumber API at http://0.0.0.0:31113
```

**Pull request merged**
